### ISSUE TITLE
Every lint is considered a "warning"

### ISSUE THREAD

**Issue by terrybrashaw** [Microsoft/vscode-typescript-tslint-plugin#34]
tslint version: 5.12.0
typescript version:  3.1.6
typescript-tslint-plugin version: 0.2.1
vscode-typescript-tslint-plugin version: 0.2.1

**Expected:**
Errors should be kept intact from tslint, showing red underlines.

`tslint.alwaysShowRuleFailuresAsWarnings` is disabled.

**Actual:**
Every lint is considered a "warning" in vscode, showing green underlines. Even explicitly specifying a lint as an error in `tslint.json` doesn't work:
```json
"typedef": {"options": ["call-signature"], "severity": "error"},
```

Running `tslint --project .` correctly lists lints with `"severity": "error"` as an error.

**Comment by mjbvz** [comment]
In your `settings.json`, try explicitly adding:

```json
    "tslint.alwaysShowRuleFailuresAsWarnings": false
```

I think the settings UI shows this option as unchecked (indicating false) when it actually is `undefined` (meaning to the default value of true)

**Comment by terrybrashaw** [comment]
Yep, it works as expected after explicitly setting it.

**Comment by mjbvz** [comment]
Thanks. This should be fixed by c35672b then

**Comment by mareksuscak** [comment]
Has this patch ever been released? Using the latest extension and this still appears to be an issue.
