### ISSUE TITLE
editor.codeActionsOnSave with "source.organizeImports", "source.fixAll" not always applied

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-typescript-tslint-plugin#51]
From https://github.com/Microsoft/vscode/issues/67482

**Repo**
1. In VS Code, set:

```json
  "editor.codeActionsOnSave": {
            "source.organizeImports": true,
            "source.fixAll": true
        }
```

1. Try saving a file with imports and tslint fixable problems (such as missing semicolons)

**Bug**
Fix all is often not run on save

See https://github.com/Microsoft/vscode/issues/67482#issuecomment-458765199 for explanation of root cause

**Comment by Kjagd** [comment]
Related:

Due to the change of applying `fixAll` first (https://github.com/Microsoft/vscode/commit/f0d1dbcd2c976ce9e7d845d01a61992b6a5f2d5f), I'm having issues with the output of `organizeImports` being formatted differently (disrespecting line length, and adding semicolons). While it would be nice if the organize action was following the same linting rules, in this case I would like `fixAll` to run *last*.

**Comment by unindented** [comment]
I have the exact same issue as @Kjagd. `organizeImports` and `tslint` have a different idea of what the imports should look like.

**Comment by mjbvz** [comment]
Should be fixed in extension version 1.2.0

**Comment by maiasmith** [comment]
This still seems to be an issue, even with extension version 1.2.0.

**Comment by Maximaximum** [comment]
The issue is still relevant. @mjbvz could you please reopen it?
